- name: install ansible, boto3, botocorne
  hosts: ansible-controller
  become: yes
  tasks:
    - name: insatll ansible
      apt:
        name: 
          - ansible
          - python3-pip
        state: present
        update_cache: yes
    - name: install python3, boto3
      pip:
        name:
          - boto3
          - botocore
          #- docker
          #- docker-compose
          #- ansible
          
      