- name: install ansible, boto3, botocorne
  hosts: ansible-controller
  become: yes
  tasks:
    - name: insatll ansible
      apt:
        name: 
          - ansible
          - python3-pip
          - python3-venv
        state: present
        update_cache: yes

# create virtual venv to install python package
    - name: create virtual venv
      command: python3 -m venv venv/ansible
      args:
        creates: venv/ansible # only run if the directory does not exist-idempotency check 

# activate virtual venv
    - name: activate virtual venv
      shell: source venv/ansible/bin/activate
      # args:
      #   chdir: venv/ansible/bin/  

    - name: install python3, boto3
      pip:
        #executable: venv/ansible/bin/pip3
        name:
          - boto3
          - botocore
          #- docker
          #- docker-compose


#deactivate virtual venv
    - name: deactivate virtual venv
      command: deactivate
      # args:
      #   chdir: venv/ansible/bin/         
          
      